FROM postgres:13.7-alpine as base_image

FROM base_image as deveopment
# RUN cd /docker-entrypoint-initdb.d/ && \
#   echo "CREATE USER ${POSTGRES_USER}; CREATE DATABASE ${POSTGRES_DB}; GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};" > init.db
